# Secret Store for AWS Secrets Manager service
# https://external-secrets.io/latest/api/secretstore/
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secrets-store
spec:
  provider:
    aws:
      # https://external-secrets.io/latest/api/spec/
      service: SecretsManager
      region: {{ .Values.templates.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
